Create Portugues br.ini
AM2R-Community-Developers/AM2R-Localizations pull request #11
Opened 2021-06-05 00:16 UTC by RevoWooD

hope the dev's like and send me tips to improve and update the translation for future updates of game!

2021-06-06 08:32 UTC, LiveLM requested changes
Needs some fixes, but other than that, great work on the translation 👍

2021-06-06 08:32 UTC, LiveLM commented on Portugues br.ini
> +GoldenTemple_Text = "Este templo fica na base de uma montanha oca. As estátuas, pedras entalhadas e seu projeto sólido confirmam que a estrutura foi construída para ser um santuário, provavelmente co
Por mas que 'Projeto' seja um tradução de 'Design', eu acho que 'Design' se encaixa melhor aqui.
```suggestion
GoldenTemple_Text = "Este templo fica na base de uma montanha oca. As estátuas, pedras entalhadas e seu design sólido confirmam que a estrutura foi construída para ser um santuário, provavelmente com propósito religioso. #O templo resistiu ao teste do tempo, mostrando o conhecimento e experiência de construção dos Chozo.# #Análises detectaram a presença de entidades robóticas estacionárias, colocadas em pontos estratégicos dentro da estrutura. Nenhum sinal de controle foi detectado, essas unidades operam de forma autônoma."
```

2021-06-06 08:32 UTC, LiveLM commented on Portugues br.ini
> +Tester_Text = "A unidade executa testes 360° de tiro real com protótipos de armas. Análises indicam que a armadura externa é resistente a armas de raio, enquanto que o interior tem proteção extra por
```suggestion
Tester_Text = "A unidade executa testes 360° de tiro real com protótipos de armas. Análises indicam que a armadura externa é resistente a armas de raio, enquanto que o interior tem proteção extra por um campo de energia que repele projéteis sólidos.# #Sistemas de reparo automático nos canhões podem restaurar os danos em questão de segundos; diagramas revelam que esses sistemas foram usados porque os canhões de modelos anteriores foram expostos a testes excessivamente violentos. Assim como o seu Traje de Força, o design modular da unidade permite adicionar ou remover equipamentos."
```

2021-06-06 08:32 UTC, LiveLM commented on Portugues br.ini
> +Square = "☐"
A ideia é legal, mas esses símbolos Unicode podem não aparecer corretamente em todas as plataformas, como o Linux ou Android. 
Por exemplo:
![AM2RUnicode](https://user-images.githubusercontent.com/34987841/120917963-7fbc1900-c6a1-11eb-8288-eb3ee75ed154.jpeg)
É melhor manter eles como texto mesmo.
```suggestion
Cross = "Cruz"
Circle = "Círculo"
Triangle = "Triângulo"
Square = "Quadrado"
```

2021-06-06 11:01 UTC, Miepee commented
I here and there saw Live saying that certain text was updated for the Trooper Logs.
While that is true, if you feel that the old text reads / feels better, feel free to use that one instead. German for example still uses the old text, because it reads a little more nicely.

2021-06-06 14:41 UTC, RevoWooD commented on Portugues br.ini
> +QueenMonster_Text = "O único organismo Metroid naturalmente capaz de gerar prole, a Rainha é o coração da espécie e mãe de todos os Metroids nascidos no SR388. Seu papel na colônia prejudicou sua mob
it was good for me too! I will change!

2021-06-06 14:50 UTC, RevoWooD commented on Portugues br.ini
> +Chozo_Text = "Os Chozo foram uma raça aviária antiga e misteriosa. #Incrivelmente avançados, eles colonizaram muitos mundos, espalhando sua mensagem de paz pelo universo. #Existem registros histórico
yeah, this word is better known than the other! I changed!

2021-06-06 14:53 UTC, RevoWooD commented on Portugues br.ini
> +IndustrialComplex_Text = "Esta fábrica monta drones trabalhadores que têm a tarefa de abastecer as instalações do SR388 com peças de troca que os mantêm funcionando de forma autônoma. #Apesar das mar
this way it really got better!

2021-06-06 14:56 UTC, RevoWooD commented on Portugues br.ini
> +PowerDistribution_Text2 = "Esta instalação é um centro de distribuição de energia. #A fiação conectada a essa instalação fornece energia para diversas estruturas da região. #A energia em excesso é ar
"complicadas" is better to understand, i changed for it!

2021-06-06 15:12 UTC, RevoWooD commented on Portugues br.ini
> +Thoth_Text2 = "A GFS Thoth é uma nave da classe Griffin. Era usada como escolta de naves de guerra da classe Olympus, mas foi convertida em uma nave de pesquisa. #Sua tripulação ajudou constantemente
idk what version has changed lol, but okay, change!

2021-06-06 15:18 UTC, RevoWooD commented on Portugues br.ini
> +AncientGuardian_Text = "Esta sentinela usa barreiras de espinhos e encurrala seus alvos em seu raio de disparo. #Seu projeto arcaico o restringe para operar com pouca energia, previnindo o uso simult
changed!

2021-06-06 15:19 UTC, RevoWooD commented on Portugues br.ini
> +NativeSpecies = "Espécie Nativa"
fixed!

2021-06-06 15:20 UTC, RevoWooD commented on Portugues br.ini
> +OmegaNest_Text = "Esta área está infestada com corpos espessos em forma de globo, compostos principalmente de carbohidratos cristalizados. #Aqueles que ainda precisam endurecer são movidos constantem
my mistake!

2021-06-06 15:21 UTC, RevoWooD commented on Portugues br.ini
> +
the author is not in "header" anymore?

2021-06-06 15:27 UTC, RevoWooD commented on Portugues br.ini
> +Square = "☐"
i only use the windows, so I thought if it works on one, it works on all. fixed!

2021-06-06 15:38 UTC, RevoWooD commented on Portugues br.ini
> +TrooperLogs_Text4 = "GFR V. Kainé# #Acho que o QG quer minimizar o envolvimento deles com os caçadores de recompensa, já que a confiança deles em resolver os "problemas" ao longo dos anos pode ter fe
I didn't know that, but thanks!

2021-06-06 15:42 UTC, Miepee commented on Portugues br.ini
> +
It is, there are two headers now.
This is a screenshot on how its gonna be used:
![grafik](https://user-images.githubusercontent.com/38186597/120930650-87ee7580-c6ee-11eb-9c1c-e65c02feddd3.png)

2021-06-06 15:47 UTC, RevoWooD commented on Portugues br.ini
> +TouchScale_Tip = "Troca o tamanho do contole na tela."
my mistake again!

2021-06-06 15:48 UTC, RevoWooD commented on Portugues br.ini
> +AnalogStick = "Direcional analalógico"
oh mistake again!

2021-06-06 15:53 UTC, RevoWooD commented
It's ok Mie! I will accept any improvements and fixes to my translation! I guess we are finished?

2021-06-06 15:54 UTC, Miepee commented
I personally want to wait for another review, and preferrably by one more guy.

2021-06-06 16:04 UTC, RevoWooD commented
Its ok, I wait!

2021-06-06 16:31 UTC, RevoWooD commented on Portugues br.ini
> +
oh! I understood!

2021-06-18 07:45 UTC, Miepee commented on Portugues br.ini
> +
You misunderstood this.
With your changes, this is how it will look like:
![grafik](https://user-images.githubusercontent.com/38186597/122525372-74f67200-d019-11eb-944c-474f52072f25.png)
It basically tries to display this: `Tradutor: RevoWooD, Ritinha/Revisor: LiveLM, Miepee R3VOWOOD, Ritinha`


I modified the text to show you how the game assembles it there.
![grafik](https://user-images.githubusercontent.com/38186597/122525769-ddddea00-d019-11eb-9625-f45149385c28.png)

2021-06-18 10:02 UTC, RevoWooD commented on Portugues br.ini
> +
so, what we need to use, the options display, or the header?

2021-06-18 10:05 UTC, Miepee commented on Portugues br.ini
> +
Both options display and Headers are used.
I know it's a bit confusing, but look at the screenshots.

The Author from the options display is a literal translation, while the authors in the header are the actual authors.

If I'm using Live's suggestion as above, it would look like this:
![grafik](https://user-images.githubusercontent.com/38186597/122544892-877aa680-d02d-11eb-9173-16108f49a51e.png)

2021-06-18 10:06 UTC, RevoWooD commented on Portugues br.ini
> +
I changed the display and header, see if it looks good

2021-06-18 10:08 UTC, Miepee commented on Portugues br.ini
> +
Don't think you intended it to look this way
![grafik](https://user-images.githubusercontent.com/38186597/122545219-e04a3f00-d02d-11eb-86d8-68a05df54bd3.png)

2021-06-18 10:10 UTC, RevoWooD commented on Portugues br.ini
> +
ohh, okay, i've looked in the german translation, i will fix it now

2021-06-18 10:13 UTC, RevoWooD commented on Portugues br.ini
> +
fixed!

2021-06-18 10:14 UTC, Miepee commented
Also for the future, could you maybe use more descriptive commit messages? :p
You can put in a commit message at the bottom here:
![grafik](https://user-images.githubusercontent.com/38186597/122545967-be9d8780-d02e-11eb-9751-941fee8b9bee.png)

2021-06-18 10:17 UTC, Miepee commented on Portugues br.ini
> +Author2 = "LiveLM"
```suggestion
Author = "R3VOWOOD, Ritinha, LiveLM,"
Author2 = ""
```
Don't really wanna attribute myself as an author, since I basically just checked basic stuff and not really any translation work.

2021-06-18 10:18 UTC, RevoWooD commented on Portugues br.ini
> +Author2 = "LiveLM"
oh, okay!

2021-06-18 10:20 UTC, RevoWooD commented
i will put description now, thanks!

2021-06-18 10:21 UTC, Miepee commented
Thanks, that makes it easier at a first glance to see what a commit is about

2021-06-27 20:07 UTC, LiveLM requested changes
I made one tiny change regarding the save menu, but other than that, no changes needed.
Tally and Chico have finished proof-reading the translation, they found no issues!

2021-06-27 20:58 UTC, RevoWooD commented on Portugues br.ini
> +GameSlot_OverwriteConfirm = "Substituir os dados do jogo?"
Ohh, that's good!
It really got better that way, I'll change it!

2021-07-10 02:52 UTC, RevoWooD commented
I have a question, what will the translation headers look like, the message that appears when we enter a new area? I don't know how to create

2021-07-13 11:11 UTC, Miepee commented
AFAIK you don't have to create those yourself. This will be taken of by someone else.

But something that me and @LiveLM noticed that there currently is a lot of text that clips. I talked with him in private to solve some issues, but you may want to speak with him as well to fix the last few remaining clips.

2021-07-14 21:55 UTC, RevoWooD commented
Okay, I want to talk about fixing these issues. I played the game and didn't found nothing, do these cuts appear only when playing without the widescreen mode? how I can contact him for more info?

2021-07-14 21:57 UTC, RevoWooD commented
I saw, some aspects cause cuts in many texts

2021-07-15 15:47 UTC, LiveLM reviewed
Miepee checked the translation and notice some clipping, I've fixed some instances but the inventory screen is really though to fix.
By the way, if you have a Discord account, you contact me there if you'd like: LiveLM#9375

2021-07-15 15:47 UTC, LiveLM commented on portuguese-br.ini
> +SpeedBooster = "ACELERADOR"
This one is complicated, most of the items don't fit in the space designated for each category.
![Screenshot_20210715_093932](https://user-images.githubusercontent.com/34987841/125796749-35eed71c-ceb5-4d51-9c2a-442c8e197e65.png)

This was fixed by removing the duplicate words. Since each section is clearly named, there's no need to repeat it in each item's name.
Powergrip and Screw Attack were slightly shortened to fit.
```suggestion
[ItemsMenu]
Suits = "TRAJES"
PowerSuit = "PROTETOR"
VariaSuit = "VARIA"
GravitySuit = "GRAVITACIONAL"
Beams = "RAIOS"
ChargeBeam = "CARREGADO"
IceBeam = "GELO"
WaveBeam = "ONDULAR"
SpazerBeam = "DIFUSO"
PlasmaBeam =  "PLASMA"
Misc = "OUTROS"
MorphBall = "FORMA ESFÉRICA"
SpiderBall = "ESFERA ADERENTE"
SpringBall = "ESFERA SALTADORA"
Bombs = "BOMBAS"
PowerGrip = "GARRA D. FORÇA"
ScrewAttack = "ATAQ. GIRATÓRIO"
Boots = "BOTAS"
HiJumpBoots = "SUPER PULO"
SpaceJump = "PULO ESPACIAL"
SpeedBooster = "ACELERADOR"
```
![image](https://user-images.githubusercontent.com/34987841/125798018-43925d08-3fb6-4263-bf98-29f99988bb0f.png)
The problem is that the Morphball, Spiderball and Springball don't have a easy fix.
Your translation is great, but the word 'Esfera' is just too big to fit with the font the game uses
![image](https://user-images.githubusercontent.com/34987841/125807494-1e0024e8-0bb1-456c-87b3-9ee3d6f872d3.png)

I've tried a couple of things to make the text fit, but none of them sound as good as yours.
Take a look at these options, what do you think?

![Screenshot_20210715_095207](https://user-images.githubusercontent.com/34987841/125813809-cab28030-aff6-49ef-8fc8-8a839b191b48.png)
![Screenshot_20210715_095215](https://user-images.githubusercontent.com/34987841/125813813-75fe42cc-34a2-46e2-b5a4-187f13ef489a.png)
These are the only ones that fit:
Changing it to 'Bola' would require changing the word 'Esfera' in the entire text (and doesn't sound as good imo) 
![Screenshot_20210715_095012](https://user-images.githubusercontent.com/34987841/125813807-df1658c2-e33e-4af5-8e9c-73fd5fec91e2.png)
![Screenshot_20210715_095308](https://user-images.githubusercontent.com/34987841/125813818-33c7dcec-07e5-4d60-9f60-1c582f85ba6f.png)
Miepee pointed out that having the Spiderball and Springball be their own 'Form' sounds weird, since they're 'addons' to the Morphball, as opposed to being a separate item.

I don't know what's the best way to proceed here. I've talked about this with Chico and Tally but haven't been able to come up with a solution that sounds good. Using 'Esfera' would be the best option but that doesn't fit soo....
![Screenshot_20210715_095509](https://user-images.githubusercontent.com/34987841/125813824-e72cfa30-a233-42cb-9af7-fa99ab5658c6.png)

2021-07-16 18:47 UTC, RevoWooD commented on portuguese-br.ini
> +SpiderballActivation_Classic_Tip = "[Baixo] quando estiver na Forma Esférica para ativar, [Pular] para desativar"
Okay, fixed!

2021-07-16 19:19 UTC, RevoWooD commented on portuguese-br.ini
> +SpeedBooster = "ACELERADOR"
I think better to keep "Forma Esférica", and to fix the words, how about using the same solution as "" and "" use a dot to cut the words?
like this
[](url)
```suggestion
[ItemsMenu]
Suits = "TRAJES"
PowerSuit = "PROTETOR"
VariaSuit = "VARIA"
GravitySuit = "GRAVITACIONAL"
Beams = "RAIOS"
ChargeBeam = "CARREGADO"
IceBeam = "GELO"
WaveBeam = "ONDULAR"
SpazerBeam = "DIFUSO"
PlasmaBeam =  "PLASMA"
Misc = "OUTROS"
MorphBall = "FORMA ESFÉRICA"
SpiderBall = "ESF. ADERENTE"
SpringBall = "ESF. SALTADORA"
Bombs = "BOMBAS"
PowerGrip = "GARRA D FORÇA"
ScrewAttack = "ATAQ. GIRATÓRIO"
Boots = "BOTAS"
HiJumpBoots = "SUPER PULO"
SpaceJump = "PULO ESPACIAL"
SpeedBooster = "ACELERADOR"
```

2021-07-16 19:26 UTC, RevoWooD commented on portuguese-br.ini
> +ExtremeMetroids_Tip = "Aumenta a quantidade e o dano dos Metroids do Laboratório de Genética"
Will the code go back to "monsters"? if I use it, the text shows "[!]"

2021-07-16 19:28 UTC, Miepee commented on portuguese-br.ini
> +ExtremeMetroids_Tip = "Aumenta a quantidade e o dano dos Metroids do Laboratório de Genética"
You are probably testing on 1.5.2, where it still uses "Metroids".
For 1.5.3+ they'll use "Monsters" instead. Due to 1.5.3 only being accessible as source rn, it's not being able to publically get tested.

2021-07-16 20:06 UTC, RevoWooD commented on portuguese-br.ini
> +ExtremeMetroids_Tip = "Aumenta a quantidade e o dano dos Metroids do Laboratório de Genética"
Ohh, I understand, I changed "Metroid2" to "Monster2", is it correct?

2021-07-17 15:31 UTC, Miepee commented on portuguese-br.ini
> +ExtremeMetroids_Tip = "Aumenta a quantidade e o dano dos Metroids do Laboratório de Genética"
Yep

2021-07-25 12:35 UTC, Miepee commented
You still misunderstood how the Author text works.
![grafik](https://user-images.githubusercontent.com/38186597/126898949-02476063-4e41-40cb-88e4-85a7b8372a4f.png)

This was how it was before:
![grafik](https://user-images.githubusercontent.com/38186597/126899121-e76ae580-807c-4037-92b8-28320c0d1433.png)

Would suggest to just reverting your latest commit, it was good before.

2021-07-25 13:00 UTC, Miepee reviewed
Found a few other things as well

2021-07-25 16:08 UTC, RevoWooD commented on portuguese-br.ini
> +Widescreen_Tip = "Fica em widescreen. Requer uma transição de sala para ter efeito no jogo"
Yeah, at least here in Brazil the term "Widescreen" is often used even in monitor sales advertisements

2021-07-25 16:12 UTC, RevoWooD commented on portuguese-br.ini
> +Save25 = "GFS Thoth"
Yeah, I can change to "Nave da Federação Galática" (NFG), but I need to know a good translation for "Thoth"

2021-07-25 16:15 UTC, RevoWooD commented on portuguese-br.ini
> +Save25 = "GFS Thoth"
the only word I found was "Totem"

2021-07-25 16:19 UTC, RevoWooD commented on portuguese-br.ini
> +Nuclei_Text = "REGISTRO DE ASH N. 68# #NOTAS DO PESQUISADOR:#A Lava Metroid transporta quatro órgãos "núcleos" utilizados principalmente para estocar a energia absorvida de presas. Para proteção, dis
fixed

2021-07-25 16:23 UTC, RevoWooD commented on portuguese-br.ini
> +DPadRebind_Tip = "Permite que o movimento direcional seja remapeado para botões individuais"
Fixed, thanks!

2021-07-25 16:24 UTC, RevoWooD commented on portuguese-br.ini
> +TrooperLogs_Text8 = "SPC F. Mac# #O acampamento já era. Blain e eu corremos para o elevador quando um Metroid água-viva mordeu nele. Aquele idiota enfiou uma bomba de demolição em sua boca. A próxima
I will search for it

2021-07-25 16:34 UTC, RevoWooD commented
> You still misunderstood how the Author text works.
> ![grafik](https://user-images.githubusercontent.com/38186597/126898949-02476063-4e41-40cb-88e4-85a7b8372a4f.png)
> 
> This was how it was before:
> ![grafik](https://user-images.githubusercontent.com/38186597/126899121-e76ae580-807c-4037-92b8-28320c0d1433.png)
> 
> Would suggest to just reverting your latest commit, it was good before.

I have reverted, but I wanted to test in another way..

[Header]
Language = "Português (BR)"
Author = "Ajudante: Ritinha"
Author2 = "Revisores: LiveLM, Miepee"
Version = "1.5.3"

[OptionsDisplay]
Author = "Tradutor: R3VOWOOD"

Does this look good?

2021-07-25 16:42 UTC, RevoWooD commented on portuguese-br.ini
> +Widescreen_Tip = "Fica em widescreen. Requer uma transição de sala para ter efeito no jogo"
But if you want we can change it to "Formato Panorâmico", "Fica no formato 16:9. Requer uma transição de sala para ter efeito no jogo"

2021-07-25 17:11 UTC, LiveLM commented on portuguese-br.ini
> +Widescreen_Tip = "Fica em widescreen. Requer uma transição de sala para ter efeito no jogo"
@Miepee Widescreen is a widely used term here, keeping it untranslated is better.

2021-07-25 17:14 UTC, Miepee commented on portuguese-br.ini
> +Save25 = "GFS Thoth"
`Thoth` is a proper noun / name, it doesn't have a translation.
But if that name sounds off in PT-BR, feel free to change it to something else, it's often done in localizations.

2021-07-25 17:26 UTC, Miepee commented
IMO I'd rather not classify translators.
Also, I mentioned already, that I don't want to be part of the credits :)

2021-07-25 17:44 UTC, LiveLM commented on portuguese-br.ini
> +CompatibilityMode_Tip = "Define a entrada para ser lida como códigos de tecla física em vez de virtuais"
It works fine but the text clips, even on Widescreen.
![Screenshot_20210725_144308](https://user-images.githubusercontent.com/34987841/126908249-407c201d-1da9-4a7f-b82c-2a2808758b96.png)
Maybe we can shorten it like this?

```suggestion
CompatibilityMode_Tip = "Faz a entrada ser lida como códigos de tecla física em vez de virtuais"
```
![image](https://user-images.githubusercontent.com/34987841/126908267-664dc7ba-29b6-464e-b12c-b2a9c07d6402.png)

2021-07-25 17:49 UTC, RevoWooD commented on portuguese-br.ini
> +Save25 = "GFS Thoth"
Oh, in that case it's better to keep the name, I think it's nice to pronounce

2021-07-25 17:49 UTC, RevoWooD commented on portuguese-br.ini
> +Thoth_Text2 = "Comedores de carniça se aproximaram das redondezas devido ao odor de decomposição que estava preso dentro do Thoth.##---##A GFS Thoth é uma nave da classe Griffin. Era usada como escol
changed!

2021-07-25 17:49 UTC, RevoWooD commented
> IMO I'd rather not classify translators.
> Also, I mentioned already, that I don't want to be part of the credits :)

oh! sure!

2021-07-25 18:06 UTC, RevoWooD commented on portuguese-br.ini
> +TrooperLogs_Text8 = "SPC F. Mac# #O acampamento já era. Blain e eu corremos para o elevador quando um Metroid água-viva mordeu nele. Aquele idiota enfiou uma bomba de demolição em sua boca. A próxima
Okay, this is going to be difficult as US military posts are different from Brazilian ones. They are not structured in the same way, in Brazil they are divided into two careers, officers and enlisted men, in the US there is a third career that is hierarchically between these two, warrant officers.
All posts and positions in this career do not exist in Brazil, and in this case the "GSGT S. Oracca" technically does not exist here.

But I can try to find plausible alternatives for these ranks

2021-07-25 18:45 UTC, RevoWooD commented on portuguese-br.ini
> +TrooperLogs_Text8 = "SPC F. Mac# #O acampamento já era. Blain e eu corremos para o elevador quando um Metroid água-viva mordeu nele. Aquele idiota enfiou uma bomba de demolição em sua boca. A próxima
I finished... I guess

2021-07-25 18:47 UTC, RevoWooD commented on portuguese-br.ini
> +CompatibilityMode_Tip = "Define a entrada para ser lida como códigos de tecla física em vez de virtuais"
Sure!

2021-07-25 20:27 UTC, Miepee reviewed
Last thing

2021-07-25 20:27 UTC, Miepee commented on portuguese-br.ini
> +PressStart = "Iniciar"
Don't know brazil that much, but maybe you wanna change this a bit much?
Something along the lines of "Press Start" instead of just "Start". TouchStart is `Toque para iniciar` so maybe make it a little closer to that.

2021-07-25 20:33 UTC, RevoWooD commented on portuguese-br.ini
> +PressStart = "Iniciar"
Oh yeah, I was kind of worried about that because on this screen it will go to the menu even if you press any key other than "start", so I just put that in, but do you think it's better to put "Press any key to start" ("Pressione qualquer tecla para iniciar?")

2021-07-25 21:27 UTC, RevoWooD commented on portuguese-br.ini
> +PressStart = "Iniciar"
I understand now, solved

2021-07-27 07:14 UTC, Miepee commented
Can't find any errors anymore, will merge now.

2021-07-27 07:15 UTC, merged