brazilian translation plus request
AM2R-Community-Developers/AM2R-Localizations pull request #8
Opened 2021-04-22 17:07 UTC by Felipefpl

Hi, i did this translation for am2r, it's fully done and i reviewed through several dictionaries. I wanted to report that the GUI needs to be redone because most of times the portuguese words are bigger than the words in english language, the GUI cant fully display the words/phrases in several places.

Also, the fonts are hard to see, it would be good if the fonts didnt have jagged borders.

2021-04-22 17:10 UTC, Miepee commented
@LiveLM could you review this one?

@peachflavored I know that you're EU portuguese, but could you quickly look over this, to see if you can find anything obvious that sticks out?

2021-04-22 17:13 UTC, Miepee commented
> I wanted to report that the GUI needs to be redone because most of times the portuguese words are bigger than the words in english language, the GUI cant fully display the words/phrases in several places.
@Felipefpl wait, is this related to a GUI in AM2R, or the AM2RLauncher? Could you provide Screenshots on what you mean?

2021-04-22 17:27 UTC, Miepee requested changes
I don't speak portuguese, but found a few things.

2021-04-22 17:27 UTC, Miepee commented on brazilian portuguese.ini
> +Ex = "Abaixo estão todos os campos que foram adicionados no arquivo de idioma nas atualizações."
This text is not supposed to be translated
```suggestion
Ex = "Below are all the fields that were added to the language file in the updates."
```

2021-04-22 17:27 UTC, Miepee commented on brazilian portuguese.ini
> +Author2 = "Felipe"
Was DoctorM64 really part of this translation?
I doubt that, you probably want it like this instead:
```suggestion
Author = "Felipe"
Author2 = ""
```

2021-04-22 22:25 UTC, peachflavored commented on brazilian portuguese.ini
> +Author = "Autor:"
```suggestion
Author = "Tradução:"

```

2021-04-22 22:34 UTC, peachflavored commented on brazilian portuguese.ini
> +JumpBall = "Bola da Primavera"
```suggestion
JumpBall = "Bola de Mola"

```

2021-04-22 22:37 UTC, peachflavored commented on brazilian portuguese.ini
> +ClearTime = "LIMPAR TEMPO"
```suggestion
ClearTime = "TEMPO TOTAL"

```

2021-04-22 22:37 UTC, peachflavored commented on brazilian portuguese.ini
> +SpringBall = "BOLA DA PRIMAVERA"
```suggestion
SpringBall = "BOLA DA MOLA"

```

2021-04-22 22:40 UTC, Felipefpl commented on brazilian portuguese.ini
> +Author = "Autor:"
Sorry but i dont agree with this, this line was translated literally and there is no loss of meaning at all.

2021-04-22 22:41 UTC, Felipefpl commented on brazilian portuguese.ini
> +ClearTime = "LIMPAR TEMPO"
The same applies here, The litteral translation doesnt prevent anyone from understanding what is written.

2021-04-22 22:43 UTC, peachflavored commented
I gave it a look and other than the suggested changes I made this looks okay for PT-BR. Also I should point some instances of the word **"Metroid"** are in lower case (**metroid**) so I'd suggest those to be changed too to keep everything more cohesive.

2021-04-22 22:47 UTC, peachflavored commented on brazilian portuguese.ini
> +ClearTime = "LIMPAR TEMPO"
"LIMPAR TEMPO" doesn't make any sense in PT-PT or PT-BR as it's too literal. I think "TEMPO TOTAL" is a better translation for this particular case.

2021-04-22 22:49 UTC, peachflavored commented on brazilian portuguese.ini
> +Author = "Autor:"
"Tradução", "Tradutor" or "Tradução/Revisão" is better applied in this context as you can add more people, namely the proof-readers since they helped as well.

2021-04-22 22:57 UTC, Felipefpl commented on brazilian portuguese.ini
> +ClearTime = "LIMPAR TEMPO"
i dont understand, since what i think wont matter why not just make the changes and submit the translation at once?

2021-04-22 23:05 UTC, peachflavored commented on brazilian portuguese.ini
> +ClearTime = "LIMPAR TEMPO"
I just suggesting changes I deem necessary since I was asked. I'm not in charge of anything around here mate. :) More people will see your translation and maybe suggested other changes too. My PT-PT translation was also submitted and changed in some fields that needed to be changed.

2021-04-22 23:16 UTC, LiveLM commented on brazilian portuguese.ini
> +ClearTime = "LIMPAR TEMPO"
What you think **does** matter, which is why we making suggestions and discussing changes.
Translating a project is not easy, and we want each translation to be the best they can be when they get merged into the game.

2021-04-22 23:16 UTC, Felipefpl commented
how do i update the pull request here? do i have to create another one? i fixed the lower cases of metroid.

2021-04-22 23:20 UTC, Lojemiru commented
I'm seeing some confusion in this discussion, so allow me to clear something up:

Literal word-for-word translations are almost always bad. If we wanted literal word-for-word translations, we would just use Google Translate and do all of it ourselves, because that'd give us about the same result most of the time. What we're looking for with language file PRs are _localizations_, interpretations of the original meaning into the native language. That can mean different words, phrasing, etc. so long as it carries the original meaning in a way that the language speakers can understand from a language and cultural standpoint. Sometimes things are able to be translated literally; sometimes they aren't. There seems to be an emphasis on only doing literal word-for-word translations here, which will likely result in us rejecting this PR on a quality basis if it continues. We greatly appreciate any desire to offer a new language file, but we have to try to maintain some basic level of quality.

Additionally, we cannot rework the GUI or fonts at this point in time, so any length issues will have to find another solution.

2021-04-22 23:24 UTC, Felipefpl commented
> 
> 
> I'm seeing some confusion in this discussion, so allow me to clear something up:
> 
> Literal word-for-word translations are almost always bad. If we wanted literal word-for-word translations, we would just use Google Translate and do all of it ourselves, because that'd give us about the same result most of the time. What we're looking for with language file PRs are _localizations_, interpretations of the original meaning into the native language. That can mean different words, phrasing, etc. so long as it carries the original meaning in a way that the language speakers can understand from a language and cultural standpoint. Sometimes things are able to be translated literally; sometimes they aren't. There seems to be an emphasis on only doing literal word-for-word translations here, which will likely result in us rejecting this PR on a quality basis if it continues. We greatly appreciate any desire to offer a new language file, but we have to try to maintain some basic level of quality.
> 
> Additionally, we cannot rework the GUI or fonts at this point in time, so any length issues will have to find another solution.

I can assure you of these:

1 - Literal translations arent a problem if everyone can understand what is written perfectly, i can assure you everyone wont have a problem with my translation.

2 - Literal translations are the best way to keep the original intention of the author intact, of course i dont translate EVERYTHING literally, i take exceptions when i know something cant be understood. ;)

2021-04-22 23:24 UTC, LiveLM commented
> how do i update the pull request here? do i have to create another one? i fixed the lower cases of metroid. didnt find anything to send a file here.

Pull requests are automatically updated when you make changes in your repo. Take a look, the fix you made has already [showed up here](https://github.com/AM2R-Community-Developers/AM2R-Localizations/pull/8/commits/70bc0892361a276e5b10a3465fc698cfd1eaadda)

2021-04-22 23:25 UTC, Lojemiru commented
> > I'm seeing some confusion in this discussion, so allow me to clear something up:
> > Literal word-for-word translations are almost always bad. If we wanted literal word-for-word translations, we would just use Google Translate and do all of it ourselves, because that'd give us about the same result most of the time. What we're looking for with language file PRs are _localizations_, interpretations of the original meaning into the native language. That can mean different words, phrasing, etc. so long as it carries the original meaning in a way that the language speakers can understand from a language and cultural standpoint. Sometimes things are able to be translated literally; sometimes they aren't. There seems to be an emphasis on only doing literal word-for-word translations here, which will likely result in us rejecting this PR on a quality basis if it continues. We greatly appreciate any desire to offer a new language file, but we have to try to maintain some basic level of quality.
> > Additionally, we cannot rework the GUI or fonts at this point in time, so any length issues will have to find another solution.
> 
> I can assure you of these:
> 
> 1 - Literal translations arent a problem if everyone can understand what is written perfectly, i can assure you everyone wont have a problem with my translation.
> 
> 2 - Literal translations are the best way to keep the original intention of the author intact, of course i dont translate EVERYTHING literally, i take exceptions when i know something cant be understood. ;)

Cool, just making sure we're on the same page.

2021-04-22 23:26 UTC, Felipefpl commented
> 
> 
> > how do i update the pull request here? do i have to create another one? i fixed the lower cases of metroid. didnt find anything to send a file here.
> 
> Pull requests are automatically updated when you make changes in your repo. Take a look, the fix you made has already [showed up here](https://github.com/AM2R-Community-Developers/AM2R-Localizations/pull/8/commits/70bc0892361a276e5b10a3465fc698cfd1eaadda)

@LiveLM - thank you very much for the tip, it's done then.

2021-04-23 12:23 UTC, closed without merging

2021-04-23 12:23 UTC, Miepee commented
Any reason for closing this?
Do you not want this to be merged anymore?